name: Deploy to VPS

on:
  push:
    branches:
      - main # Ganti dengan branch yang Anda gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code dari GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH untuk VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_LUPIZ_SRV }}

      # Step 3: Copy files ke VPS dan restart Docker
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no lupizzelit@103.127.135.194 "
            cd /path/to/repository &&
            git pull &&
            sudo docker-compose down &&
            sudo docker-compose up -d"
