name: Deploy to VPS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH untuk koneksi ke VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_LUPIZ_SRV }}

      # Step 3: Test SSH connection
      - name: Test SSH Connection
        run: ssh -o StrictHostKeyChecking=yes lupizzelit@103.127.135.194 "echo Connected successfully!"

      # Step 4: Deploy ke VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=yes lupizzelit@103.127.135.194 << 'EOF'
            cd /home/lupizzelit/lupiz-srv-nginx || { echo "Project path not found!"; exit 1; }
            git pull || { echo "Git pull failed!"; exit 1; }
            sudo docker-compose down || { echo "Docker-compose down failed!"; exit 1; }
            sudo docker-compose up -d || { echo "Docker-compose up failed!"; exit 1; }
          EOF
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}
