name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up SSH untuk koneksi ke VPS
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_LUPIZ_SRV }}

      # Step 3: Deploy ke VPS
      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no lupizzelit@103.127.135.194 "
            git pull &&
            sudo ./docker
